steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--file"
      - "Dockerfile"
      - "--tag"
      - "asia-southeast3-docker.pkg.dev/santa-web-509114/santa/santa-ui:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-southeast3-docker.pkg.dev/santa-web-509114/santa/santa-ui:$SHORT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "santa-ui"
      - "--image"
      - "asia-southeast3-docker.pkg.dev/santa-web-509114/santa/santa-ui:$SHORT_SHA"
      - "--region"
      - "asia-southeast3"
      - "--platform"
      - "managed"
      - "--service-account"
      - "santa-ui-runtime@santa-web-509114.iam.gserviceaccount.com"
      - "--quiet"

images:
  - "asia-southeast3-docker.pkg.dev/santa-web-509114/santa/santa-ui:$SHORT_SHA"

options:
  logging: "CLOUD_LOGGING_ONLY"
