"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import type { Locale } from "@/lib/i18n";
import { showErrorToast } from "@/lib/toast";

type Address = { id: string; recipientName: string; phoneNumber: string; addressLine1: string; addressLine2: string | null; subdistrict: string; district: string; province: string; postalCode: string };
type AddressForm = Omit<Address, "id">;
type Geography = { getProvinces: () => string[]; getDistricts: (province: string) => string[]; getSubDistricts: (province: string, district: string) => string[]; getzip_code: (province: string, district: string, subdistrict: string) => string | undefined; loadData: () => Promise<void> };
const blankForm: AddressForm = { recipientName: "", phoneNumber: "", addressLine1: "", addressLine2: "", subdistrict: "", district: "", province: "", postalCode: "" };
const copy = { th: { address: "บ้านเลขที่ หมู่ ซอย ถนน", address2: "อาคาร ชั้น หมู่บ้าน (ถ้ามี)", cancel: "ยกเลิก", delete: "ลบที่อยู่", deleteConfirm: "ลบที่อยู่จัดส่งนี้ใช่หรือไม่?", district: "เขต / อำเภอ", edit: "แก้ไขที่อยู่", empty: "คุณยังไม่ได้บันทึกที่อยู่จัดส่ง", error: "บันทึกที่อยู่ไม่สำเร็จ", loading: "กำลังโหลดข้อมูล...", phone: "เบอร์โทรศัพท์", postalCode: "รหัสไปรษณีย์", province: "จังหวัด", recipient: "ชื่อผู้รับ", save: "บันทึกที่อยู่", subdistrict: "แขวง / ตำบล", title: "ที่อยู่จัดส่ง", selectDistrict: "เลือกเขต / อำเภอ", selectProvince: "เลือกจังหวัด", selectSubdistrict: "เลือกแขวง / ตำบล" }, en: { address: "House no., village, lane, road", address2: "Building, floor, village (optional)", cancel: "Cancel", delete: "Delete address", deleteConfirm: "Delete this delivery address?", district: "District", edit: "Edit address", empty: "You have no saved delivery address.", error: "Unable to save the address", loading: "Loading address data...", phone: "Phone number", postalCode: "Postal code", province: "Province", recipient: "Recipient name", save: "Save address", subdistrict: "Subdistrict", title: "Delivery address", selectDistrict: "Select district", selectProvince: "Select province", selectSubdistrict: "Select subdistrict" } } as const;

export function CustomerDeliveryAddresses({ locale }: { locale: Locale }) {
  const text = copy[locale];
  const [address, setAddress] = useState<Address | null>(null);
  const [form, setForm] = useState<AddressForm>(blankForm);
  const [geo, setGeo] = useState<Geography | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const load = useCallback(async () => { setIsLoading(true); try { const response = await fetch("/api/customer/delivery-addresses", { cache: "no-store" }); if (!response.ok) throw new Error(); const result = await response.json() as Address | null; setAddress(result); setForm(result ? toForm(result) : blankForm); } catch { showErrorToast(text.error); } finally { setIsLoading(false); } }, [text.error]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { let active = true; void import("thai-address-select").then(async (module) => { await module.loadData(); if (active) setGeo(module); }); return () => { active = false; }; }, []);
  const provinces = useMemo(() => geo?.getProvinces() ?? [], [geo]);
  const districts = useMemo(() => form.province ? geo?.getDistricts(form.province) ?? [] : [], [form.province, geo]);
  const subdistricts = useMemo(() => form.province && form.district ? geo?.getSubDistricts(form.province, form.district) ?? [] : [], [form.province, form.district, geo]);
  function update<K extends keyof AddressForm>(field: K, value: AddressForm[K]) { setForm((current) => ({ ...current, [field]: value })); }
  function selectProvince(province: string) { setForm((current) => ({ ...current, province, district: "", subdistrict: "", postalCode: "" })); }
  function selectDistrict(district: string) { setForm((current) => ({ ...current, district, subdistrict: "", postalCode: "" })); }
  function selectSubdistrict(subdistrict: string) { setForm((current) => ({ ...current, subdistrict, postalCode: geo?.getzip_code(current.province, current.district, subdistrict) ?? "" })); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIsSaving(true); try { const payload = { ...form, addressLine2: form.addressLine2 || null }; const response = await fetch(address ? `/api/customer/delivery-addresses/${address.id}` : "/api/customer/delivery-addresses", { method: address ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) throw new Error(result?.message ?? text.error); setIsEditing(false); await load(); } catch (error) { showErrorToast(text.error, error instanceof Error ? error.message : undefined); } finally { setIsSaving(false); } }
  async function remove() { if (!address || !window.confirm(text.deleteConfirm)) return; try { const response = await fetch(`/api/customer/delivery-addresses/${address.id}`, { method: "DELETE" }); if (!response.ok) throw new Error(); setAddress(null); setForm(blankForm); } catch { showErrorToast(text.error); } }
  if (isLoading || !geo) return <article className="customer-account-panel customer-deliveries-panel"><h2>{text.title}</h2><p className="customer-address-loading">{text.loading}</p></article>;
  return <article className="customer-account-panel customer-deliveries-panel"><div className="customer-deliveries-heading"><h2>{text.title}</h2>{address && !isEditing ? <button className="customer-address-add" onClick={() => setIsEditing(true)} type="button">{text.edit}</button> : null}</div>{address && !isEditing ? <div className="customer-address-list"><article className="customer-address-card"><p><strong>{address.recipientName}</strong> · {address.phoneNumber}</p><p>{formatAddress(address, locale)}</p><button className="customer-address-delete" onClick={() => void remove()} type="button">{text.delete}</button></article></div> : <><p className="customer-address-intro">{address ? "" : text.empty}</p><AddressEditor districts={districts} form={form} isSaving={isSaving} onCancel={() => { setIsEditing(false); setForm(address ? toForm(address) : blankForm); }} onChange={update} onDistrict={selectDistrict} onProvince={selectProvince} onSave={save} onSubdistrict={selectSubdistrict} provinces={provinces} subdistricts={subdistricts} text={text} /></>}</article>;
}

function AddressEditor({ districts, form, isSaving, onCancel, onChange, onDistrict, onProvince, onSave, onSubdistrict, provinces, subdistricts, text }: { districts: string[]; form: AddressForm; isSaving: boolean; onCancel: () => void; onChange: <K extends keyof AddressForm>(field: K, value: AddressForm[K]) => void; onDistrict: (value: string) => void; onProvince: (value: string) => void; onSave: (event: FormEvent<HTMLFormElement>) => void; onSubdistrict: (value: string) => void; provinces: string[]; subdistricts: string[]; text: typeof copy.th | typeof copy.en }) {
  return <form className="customer-address-form" onSubmit={onSave}><label><span>{text.recipient}</span><input maxLength={255} onChange={(event) => onChange("recipientName", event.target.value)} required value={form.recipientName} /></label><label><span>{text.phone}</span><input inputMode="tel" onChange={(event) => onChange("phoneNumber", event.target.value)} required value={form.phoneNumber} /></label><label><span>{text.address}</span><input maxLength={255} onChange={(event) => onChange("addressLine1", event.target.value)} required value={form.addressLine1} /></label><label><span>{text.address2}</span><input maxLength={255} onChange={(event) => onChange("addressLine2", event.target.value)} value={form.addressLine2 ?? ""} /></label><label><span>{text.province}</span><select onChange={(event) => onProvince(event.target.value)} required value={form.province}><option value="">{text.selectProvince}</option>{provinces.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label><span>{text.district}</span><select disabled={!form.province} onChange={(event) => onDistrict(event.target.value)} required value={form.district}><option value="">{text.selectDistrict}</option>{districts.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label><span>{text.subdistrict}</span><select disabled={!form.district} onChange={(event) => onSubdistrict(event.target.value)} required value={form.subdistrict}><option value="">{text.selectSubdistrict}</option>{subdistricts.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label><span>{text.postalCode}</span><input readOnly value={form.postalCode} /></label><div className="customer-address-form-actions"><button className="secondary" disabled={isSaving} onClick={onCancel} type="button">{text.cancel}</button><button disabled={isSaving} type="submit">{isSaving ? "…" : text.save}</button></div></form>;
}
function toForm(address: Address): AddressForm { return { recipientName: address.recipientName, phoneNumber: address.phoneNumber, addressLine1: address.addressLine1, addressLine2: address.addressLine2, subdistrict: address.subdistrict, district: address.district, province: address.province, postalCode: address.postalCode }; }
function formatAddress(address: Address, locale: Locale) { const prefix = locale === "th" ? ["แขวง/ตำบล", "เขต/อำเภอ"] : ["Subdistrict", "District"]; return [address.addressLine1, address.addressLine2, `${prefix[0]} ${address.subdistrict}`, `${prefix[1]} ${address.district}`, address.province, address.postalCode].filter(Boolean).join(" · "); }
