"use client";

import { useCallback, useEffect, useState } from "react";
import type { Locale } from "@/lib/i18n";
import { showErrorToast, showSuccessToast } from "@/lib/toast";
import { ClientTablePagination } from "./client-table-pagination";

type Quotation = { id: string; productSku: string; productNameTh: string; productNameEn: string; fullName: string; phoneNumber: string; companyName?: string | null; email: string; requestedQuantity: number; note?: string | null; createdAt: string; acknowledgedAt?: string | null; acknowledgedBy?: string | null };
type PaginationMeta = { page: number; pageSize: number; totalItems: number; totalPages: number };

export function QuotationsSection({ locale }: { locale: Locale }) {
  const [rows, setRows] = useState<Quotation[]>([]); const [loading, setLoading] = useState(true); const [pendingId, setPendingId] = useState<string | null>(null); const [pagination, setPagination] = useState<PaginationMeta>({ page: 1, pageSize: 20, totalItems: 0, totalPages: 1 }); const thai = locale === "th";
  const load = useCallback(async (page = 1, pageSize = 20) => { setLoading(true); try { const response = await fetch(`/api/quotation-requests/admin?page=${page}&pageSize=${pageSize}`, { cache: "no-store" }); const payload = await response.json() as { items?: Quotation[]; meta?: PaginationMeta; message?: string }; if (!response.ok) throw new Error(payload.message ?? "Unable to load quotation requests."); setRows(payload.items ?? []); setPagination(payload.meta ?? { page, pageSize, totalItems: 0, totalPages: 1 }); } catch (error) { showErrorToast(thai ? "ไม่สามารถโหลดคำขอใบเสนอราคาได้" : "Unable to load quotation requests", error instanceof Error ? error.message : undefined); } finally { setLoading(false); } }, [thai]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function acknowledge(id: string) { setPendingId(id); try { const response = await fetch(`/api/quotation-requests/admin/${encodeURIComponent(id)}/acknowledge`, { method: "PATCH" }); const record = await response.json() as Quotation & { message?: string }; if (!response.ok) throw new Error(record.message ?? "Unable to acknowledge quotation request."); setRows((current) => current.map((row) => row.id === id ? record : row)); showSuccessToast(thai ? "รับทราบคำขอแล้ว" : "Request acknowledged"); } catch (error) { showErrorToast(thai ? "บันทึกสถานะไม่สำเร็จ" : "Unable to update request", error instanceof Error ? error.message : undefined); } finally { setPendingId(null); } }
  async function downloadExport() { try { const response = await fetch("/api/quotation-requests/admin/export", { cache: "no-store" }); if (!response.ok) throw new Error(); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = "quotation-requests-export.xlsx"; link.click(); URL.revokeObjectURL(url); } catch { showErrorToast(thai ? "ไม่สามารถส่งออกใบเสนอราคาได้" : "Unable to export quotation requests"); } }
  return <div className="admin-section-panel"><div className="admin-orders-heading"><div><h1 id="admin-heading">{thai ? "คำขอใบเสนอราคา" : "Quotation requests"}</h1><p>{thai ? "คำขอใหม่จะถูกส่งแจ้งไปยังอีเมลที่ตั้งค่าไว้" : "New requests are sent to the configured notification email."}</p></div><div className="admin-product-toolbar-actions"><button className="admin-product-secondary-button" onClick={() => void downloadExport()} type="button"><span className="material-symbols-outlined" aria-hidden="true">download</span>{thai ? "ส่งออก Excel" : "Export Excel"}</button><button className="admin-product-secondary-button" onClick={() => void load(1, pagination.pageSize)} type="button">{thai ? "รีเฟรช" : "Refresh"}</button></div></div><div className="admin-table-shell"><div className="admin-table-scroll"><table className="admin-data-table admin-data-table-wide"><thead><tr><th>{thai ? "สินค้า" : "Product"}</th><th>{thai ? "ผู้ขอ" : "Requester"}</th><th>{thai ? "จำนวน" : "Quantity"}</th><th>{thai ? "รายละเอียด" : "Details"}</th><th>{thai ? "สถานะ" : "Status"}</th><th>{thai ? "จัดการ" : "Action"}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{locale === "th" ? row.productNameTh : row.productNameEn}</strong><small>{row.productSku}</small></td><td><strong>{row.fullName}</strong><small>{row.companyName ?? "-"}<br />{row.phoneNumber}<br />{row.email}</small></td><td>{row.requestedQuantity}</td><td>{row.note ?? "-"}<small>{new Intl.DateTimeFormat(locale === "th" ? "th-TH" : "en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(row.createdAt))}</small></td><td><span className="admin-order-badge">{row.acknowledgedAt ? (thai ? "รับทราบแล้ว" : "Acknowledged") : (thai ? "ใหม่" : "New")}</span>{row.acknowledgedBy ? <small>{row.acknowledgedBy}</small> : null}</td><td>{row.acknowledgedAt ? "-" : <button className="admin-product-add-button admin-table-action-button" disabled={pendingId === row.id} onClick={() => void acknowledge(row.id)} type="button">{pendingId === row.id ? "…" : thai ? "รับทราบ" : "Acknowledge"}</button>}</td></tr>)}{loading ? <tr><td className="admin-table-empty-cell" colSpan={6}>{thai ? "กำลังโหลด…" : "Loading…"}</td></tr> : null}{!loading && rows.length === 0 ? <tr><td className="admin-table-empty-cell" colSpan={6}>{thai ? "ไม่พบคำขอ" : "No quotation requests found."}</td></tr> : null}</tbody></table></div><ClientTablePagination currentPage={pagination.page} currentPageSize={pagination.pageSize} disabled={loading} locale={locale} onPageChange={(page) => void load(page, pagination.pageSize)} onPageSizeChange={(pageSize) => void load(1, pageSize)} totalPages={pagination.totalPages} /></div></div>;
}
